### PR TITLE
getTimegrid fixed wrong days

### PR DESCRIPTION
**Pull request by hairy-tortoise**
before the days in for of numbers were wrongly assigned to the correct list. The time grid from Saturday or Sunday was returned as the time grid for Monday. I don't know if Saturday and Sunday are correctly matched. This has to be checked by someone else.

### CODE REVIEW

**Review by IsAvaible — CHANGES_REQUESTED** [review]
Please revert the formatting changes and limit your pull request to the bug you are adressing.

**Comment by IsAvaible** [comment]
I had a hard time finding the logic changes you made due to the different formatting, but as far as I can tell, you changed the indices in the Timegrid _fromList constructor. 
Currently, the logic adheres to the weekday sorting in the [WebUntis JSON-RPC API documentation]( https://untis-sr.ch/wp-content/uploads/2019/11/2018-09-20-WebUntis_JSON_RPC_API.pdf). The getTimegridUnits endpoint should return the time grid starting from Sunday and ending on Saturday (see page 5). 
Could you provide the raw JSON object that is returned by the API by either using `var object = await mySession.customRequest("getTimegridUnits", {});` or intercepting the network call when using `session.getTimeGrid(...)`?
Thanks for the pull request!

**Comment by LcsTh0** [comment]
> Please revert the formatting changes and limit your pull request to the bug you are adressing.

I'm sorry. I didn't realize they were made.

**Comment by LcsTh0** [comment]
> I had a hard time finding the logic changes you made due to the different formatting, but as far as I can tell, you changed the indices in the Timegrid _fromList constructor. Currently, the logic adheres to the weekday sorting in the [WebUntis JSON-RPC API documentation](https://untis-sr.ch/wp-content/uploads/2019/11/2018-09-20-WebUntis_JSON_RPC_API.pdf). The getTimegridUnits endpoint should return the time grid starting from Sunday and ending on Saturday (see page 5). Could you provide the raw JSON object that is returned by the API by either using `var object = await mySession.customRequest("getTimegridUnits", {});` or intercepting the network call when using `session.getTimeGrid(...)`? Thanks for the pull request!

I just tested it with my school and Monday was always null, so this change works for me at least.

**Comment by hairy-tortoise** [comment]
> I had a hard time finding the logic changes you made due to the different formatting, but as far as I can tell, you changed the indices in the Timegrid _fromList constructor. Currently, the logic adheres to the weekday sorting in the [WebUntis JSON-RPC API documentation](https://untis-sr.ch/wp-content/uploads/2019/11/2018-09-20-WebUntis_JSON_RPC_API.pdf). The getTimegridUnits endpoint should return the time grid starting from Sunday and ending on Saturday (see page 5). Could you provide the raw JSON object that is returned by the API by either using `var object = await mySession.customRequest("getTimegridUnits", {});` or intercepting the network call when using `session.getTimeGrid(...)`? Thanks for the pull request!

Me and my friend are working on a app together and he discovered, that at least for our school it works like this and otherwise Monday is always null. We can't confirm this with other schools, but it would be weird if they're different from each other.

**Comment by hairy-tortoise** [comment]
I don't know if this is relevant but recently in school, we did something to convert dates to weekdays and it was like this;

`switch(d) {
	case 0: erg = "Samstag"; break;
	case 1: erg = "Sonntag"; break;
	case 2: erg = "Montag"; break;
	case 3: erg = "Dienstag"; break;
	case 4: erg = "Mittwoch"; break;
	case 5: erg = "Donnerstag"; break;
	case 6: erg = "Freitag"; break;
}`

I don't know if this is some kind of standard, but for me at least the current implementation doesn't work.

**Comment by IsAvaible** [comment]
> Me and my friend are working on a app together and he discovered, that at least for our school it works like this and otherwise Monday is always null. We can't confirm this with other schools, but it would be weird if they're different from each other.

If Monday was null before your changes, Saturday should be null after switching the indices. Can you confirm whether this hypothesis is true?

> I don't know if this is relevant but recently in school, [...]

The code you used in your school depends on how the weekdays are mapped onto the integers, and does not apply if the weekdays are sorted to start with Sunday instead of Saturday.

> Could you provide the raw JSON object that is returned by the API by either using var object = await mySession.customRequest("getTimegridUnits", {}); or intercepting the network call when using session.getTimeGrid(...)?

This way we can make sure that the response of the API changed.

**Comment by hairy-tortoise** [comment]
> If Monday was null before your changes, Saturday should be null after switching the indices. Can you confirm whether this hypothesis is true?
>
Yes, I assume because I don't have school on the weekend, the time grid is null

> > Could you provide the raw JSON object that is returned by the API by either using var object = await mySession.customRequest("getTimegridUnits", {}); or intercepting the network call when using session.getTimeGrid(...)?
> 
> This way we can make sure that the response of the API changed.
>

`[{day: 2, timeUnits: [{name: 1, startTime: 740, endTime: 825}, {name: 2, startTime: 825, endTime: 910}, {name: 3, startTime: 930, endTime: 1015}, {name: 4, startTime: 1015, endTime: 1100}, {name: 5, startTime: 1115, endTime: 1200}, {name: 6, startTime: 1200, endTime: 1245}, {name: 7, startTime: 1250, endTime: 1325}, {name: 8, startTime: 1330, endTime: 1415}, {name: 9, startTime: 1415, endTime: 1500}, {name: 10, startTime: 1510, endTime: 1555}, {name: 11, startTime: 1555, endTime: 1640}, {name: 12, startTime: 1650, endTime: 1735}, {name: 13, startTime: 1745, endTime: 1830}]}, {day: 3, timeUnits: [{name: 1, startTime: 740, endTime: 825}, {name: 2, startTime: 825, endTime: 910}, {name: 3, startTime: 930, endTime: 1015}, {name: 4, startTime: 1015, endTime: 1100}, {name: 5, startTime: 1115, endTime: 1200}, {name: 6, startTime: 1200, endTime: 1245}, {name: 7, startTime: 1250, endTime: 1325}, {name: 8, startTime: 1330, endTime: 1415}, {name: 9, startTime: 1415, endTime: 1500}, {name: 10, startTime: 1510, endTime: 1555}, {name: 11, startTime: 1555, endTime: 1640}, {name: 12, startTime: 1650, endTime: 1735}, {name: 13, startTime: 1745, endTime: 1830}]}, {day: 4, timeUnits: [{name: 1, startTime: 740, endTime: 825}, {name: 2, startTime: 825, endTime: 910}, {name: 3, startTime: 930, endTime: 1015}, {name: 4, startTime: 1015, endTime: 1100}, {name: 5, startTime: 1115, endTime: 1200}, {name: 6, startTime: 1200, endTime: 1245}, {name: 7, startTime: 1250, endTime: 1325}, {name: 8, startTime: 1330, endTime: 1415}, {name: 9, startTime: 1415, endTime: 1500}, {name: 10, startTime: 1510, endTime: 1555}, {name: 11, startTime: 1555, endTime: 1640}, {name: 12, startTime: 1650, endTime: 1735}, {name: 13, startTime: 1745, endTime: 1830}]}, {day: 5, timeUnits: [{name: 1, startTime: 740, endTime: 825}, {name: 2, startTime: 825, endTime: 910}, {name: 3, startTime: 930, endTime: 1015}, {name: 4, startTime: 1015, endTime: 1100}, {name: 5, startTime: 1115, endTime: 1200}, {name: 6, startTime: 1200, endTime: 1245}, {name: 7, startTime: 1250, endTime: 1325}, {name: 8, startTime: 1330, endTime: 1415}, {name: 9, startTime: 1415, endTime: 1500}, {name: 10, startTime: 1510, endTime: 1555}, {name: 11, startTime: 1555, endTime: 1640}, {name: 12, startTime: 1650, endTime: 1735}, {name: 13, startTime: 1745, endTime: 1830}]}, {day: 6, timeUnits: [{name: 1, startTime: 740, endTime: 825}, {name: 2, startTime: 825, endTime: 910}, {name: 3, startTime: 930, endTime: 1015}, {name: 4, startTime: 1015, endTime: 1100}, {name: 5, startTime: 1115, endTime: 1200}, {name: 6, startTime: 1200, endTime: 1245}, {name: 7, startTime: 1250, endTime: 1325}, {name: 8, startTime: 1330, endTime: 1415}, {name: 9, startTime: 1415, endTime: 1500}, {name: 10, startTime: 1510, endTime: 1555}, {name: 11, startTime: 1555, endTime: 1640}, {name: 12, startTime: 1650, endTime: 1735}, {name: 13, startTime: 1745, endTime: 1830}]}]`

As you see only days 2 to 6 have values assigned to them.

**Comment by hairy-tortoise** [comment]
[This](https://pastebin.com/rGk9sDGU) is intercepted from the official app to confirm that the days that should be there are Monday to Friday

**Review by IsAvaible — APPROVED** [review]
Firstly, sorry for the late reply and thank you for providing the API response. It seems that the API may not return values for a day, if the day has not been filled by the school and that the example or weekday indices in the API documentation are incorrect. 
As I currently can't test the response for a time grid that provides values for Saturday and Sunday myself, I suggest merging your changes and seeing if any issues arise further down the line (for users who do have lessons on Saturday or Sunday).

**Pull request merged**
